[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
    [headers.values]
  Content-Security-Policy = "frame-ancestors https://www.youtube.com"
    Access-Control-Allow-Origin = "*"