[build]
  functions = "/root"
  
[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "https://www.youtube.com/"
    [headers.values]
    Access-Control-Allow-Origin = "*"
    cache-control = '''
	max-age=0,
	no-cache,
	no-store,
	must-revalidate'''